test again

diff --git a/.github/workflows/openid.yaml b/.github/workflows/openid.yaml
--- a/.github/workflows/openid.yaml
+++ b/.github/workflows/openid.yaml
@@ -34,5 +34,10 @@ jobs:
         - name: 'S3 COPY'
           run: |
             echo "Copying file to S3 bucket"
-            aws s3 cp ./copy/* s3://fallongege-cp-pmc-bucket
+            aws s3 cp ./copy/ s3://fallongege-cp-pmc-bucket/ --recursive
+            if [ $? -eq 0 ]; then
+                echo "File copied successfully"
+            else
+                echo "Failed to copy file" >&2
+            fi
             
